### ISSUE TITLE
Nombres de variables

### ISSUE THREAD

**Issue by DanBaDo** [TwilightPhoenyx/megacontador#1]
Muy bien! 👍

Te pongo deberes: [CleanCode](https://softwarecrafters.io/javascript/clean-code-javascript)

Entiendo que muchos de los comentarios que has añadido están para servirle como "apuntes" a tu yo del futuro. Está bien... pero no debemos de abusar de los comentarios. Tener que poner un comentario diciendo qué hace el código no es buena señal. Mira el artículo que te he enlazado y si quieres discutimos sobre ello.

Felicidades!!!

**Comment by TwilightPhoenyx** [comment]
Muchas gracias!

Lo cierto es que si. Esos comentarios los escribiera  para comprender mejor e interiorizar sobre todo el funcionamiento del useEffect, aunque luego marqué más acciones. Soy consciente de que quizás me excedí con ellos un poquito. Voy a leer el articulo sobre CleanCode enlazado. Y si, me gustaría discutir sobre ello. Me interesa coger el hábito de escribir código limpio y legible para no acabar con malas costumbres.
________________________________
De: Daniel Bañobre Dopico ***@***.***>
Enviado: viernes, 3 de marzo de 2023 19:21
Para: TwilightPhoenyx/megacontador ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [TwilightPhoenyx/megacontador] Nombres de variables (Issue #1)


Muy bien! 👍

Te pongo deberes: CleanCode<https://softwarecrafters.io/javascript/clean-code-javascript>

Entiendo que muchos de los comentarios que has añadido están para servirle como "apuntes" a tu yo del futuro. Está bien... pero no debemos de abusar de los comentarios. Tener que poner un comentario diciendo qué hace el código no es buena señal. Mira el artículo que te he enlazado y si quieres discutimos sobre ello.

Felicidades!!!
